### ISSUE TITLE
h2 database vulnerability

### ISSUE THREAD

**Issue by neseleznev** [pjfanning/poi-shared-strings#6]
Hi, thank you for continuing developing such a useful library!

Our snyk yells at dependency you have
https://github.com/pjfanning/poi-shared-strings/blob/ec23c2af6ca26dc2646e44872ff8cbf602b8d8d7/build.gradle#L23

Details
https://snyk.io/vuln/SNYK-JAVA-COMH2DATABASE-31685

`There is no fixed version for com.h2database:h2.` :(
Last release was in late 2019 `Version 1.4.200 (2019-10-14)`

I see you use it not in tests, is there any chance to use something different?

**Comment by pjfanning** [comment]
poi-shared-strings usage of h2 lib is very unlikely to be affected by this issue - the h2 db used by poi-shared-strings is a temp file that is used just for indexing the shared string data.

- it is may even be possible to use poi-shared-strings without the h2 dependency
- feel free to fork this lib and come up with your own approach to indexing the shared string data

**Comment by neseleznev** [comment]
Oh I see, there is nothing in common with DB. I'm going to ignore this warning better.

Thank you!

**Comment by pjfanning** [comment]
https://github.com/h2database/h2database/issues/1225

Just in case anyone else is interested - h2 team have good points in this issue
